-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS ATM_MACHINE
-- CHARACTER SET utf8mb4
-- COLLATE utf8mb4_general_ci
;

-- Switch to the ATM_MACHINE database
USE ATM_MACHINE;

-- Create the RECORDS table if it doesn't exist
CREATE TABLE IF NOT EXISTS RECORDS (
    ACCONT_NO INT(4) PRIMARY KEY,
    PASSWORD INT(3),
    NAME VARCHAR(20),
    CR_AMT INT DEFAULT 0,
    WITHDRAWL INT DEFAULT 0,
    BALANCE INT DEFAULT 0
);

-- Insert sample data into the RECORDS table
-- Only insert if the account does not already exist

INSERT INTO RECORDS (ACCONT_NO, PASSWORD, NAME, CR_AMT, WITHDRAWL, BALANCE)
SELECT 1001, 123, 'John Doe', 5000, 0, 5000
WHERE NOT EXISTS (SELECT 1 FROM RECORDS WHERE ACCONT_NO = 1001);

INSERT INTO RECORDS (ACCONT_NO, PASSWORD, NAME, CR_AMT, WITHDRAWL, BALANCE)
SELECT 1002, 234, 'Jane Smith', 2000, 0, 2000
WHERE NOT EXISTS (SELECT 1 FROM RECORDS WHERE ACCONT_NO = 1002);

INSERT INTO RECORDS (ACCONT_NO, PASSWORD, NAME, CR_AMT, WITHDRAWL, BALANCE)
SELECT 1003, 345, 'Alice Brown', 1000, 0, 1000
WHERE NOT EXISTS (SELECT 1 FROM RECORDS WHERE ACCONT_NO = 1003);

INSERT INTO RECORDS (ACCONT_NO, PASSWORD, NAME, CR_AMT, WITHDRAWL, BALANCE)
SELECT 1004, 456, 'Bob White', 3000, 0, 3000
WHERE NOT EXISTS (SELECT 1 FROM RECORDS WHERE ACCONT_NO = 1004);

-- Confirm that the records were inserted
SELECT * FROM RECORDS;
